### PR TITLE
find_services: add lot parameter

### PR DESCRIPTION
**Pull request by risicle**
which was already supported by API but not exposed here. Bump to 3.8.0

### CODE REVIEW

**Comment by allait** [comment]
Did we check that none of the callers pass positional arguments after `frameworks`? Otherwise this is a breaking change.

**Comment by risicle** [comment]
Hmm good point.

**Comment by risicle** [comment]
/me hates the positional/keyword arg clash situation. wish they were mutually exclusive or something

**Comment by risicle** [comment]
Hold on, I can just move the kwarg to the end of the call signature. And here was me about to do an audit of all call sites. Will rehash.

**Comment by TheDoubleK** [comment]
:+1: good to go.

**Comment by risicle** [comment]
wheee!

**Pull request merged**
