### PR TITLE
Audit types: add three process outcome related audit types

### PR DESCRIPTION
**Pull request by risicle**
Trello https://trello.com/c/4JtM91iv/67-create-back-end-interface-for-award-flow

### CODE REVIEW

**Comment by benvand** [comment]
What's a 'process'? Seems a bit of a vague wording at a glance. Are we married to that?

**Comment by risicle** [comment]
It's a purchasing process. I couldn't think of a better term for it. If you don't like that you'd better not look at https://github.com/alphagov/digitalmarketplace-api/pull/791

**Comment by risicle** [comment]
Basically it's a generalization of a "Brief" or a direct award "Project".

**Comment by risicle** [comment]
Removed referenced to "process outcomes" in favour of straight "outcomes"

**Pull request merged**
